/**
 * --serve: the stdio MCP server over streamable HTTP, plus the human-facing
 * payment surface. One node:http server, zero dependencies:
 *
 *   POST /mcp            MCP streamable HTTP (stateless): one JSON-RPC message in,
 *                        its response out. Notifications → 202. The same
 *                        createDispatcher() that powers stdio handles everything.
 *                        tools/call from an SSE-capable client answers as an
 *                        event stream with progress heartbeats — generations
 *                        and payment waits outlive client tool timeouts. On a paid
 *                        server the first call returns the payment-required quote;
 *                        the follow-up _payment_id call is what's held open through
 *                        payment (so the caller never re-invokes AFTER paying).
 *   GET  /               landing page: hero connect command (Claude/Grok toggle), how payment
 *                        flows, tool list w/ per-workflow editor links, self-hosting + author-payout story
 *   GET  /llms.txt       the same story as plain text, written for agents
 *   GET  /graph/:name.json  a served workflow's raw graph JSON, exactly as loaded
 *   GET  /pay/:id        self-contained pay page — QR code, exact amount, live status
 *   GET  /x402/status/:id  quote status JSON; ?wait=1 long-polls up to 25s
 *   GET  /x402/watch/:id   SSE: one `status` event per state change, closes on settle
 *                        (the pay page subscribes to it; falls back to /x402/status)
 *   GET  /out/:file      generated media (unguessable filenames), when an outDir is given
 *   GET  /favicon.ico|/favicon.png|/apple-touch-icon.png|/icon-512.png|/og.jpg
 *                        brand assets from assets/ — the icon and the social (OG) card,
 *                        both generated by nanoodle workflows (see assets/README.md)
 *
 * POST requires Content-Type: application/json — browsers can't send that
 * cross-origin without a CORS preflight, which (with the default localhost
 * bind) is the DNS-rebinding guard. There is no session state to steal and no
 * cookie auth; on a paid server, the payment itself is the authorization.
 */
import http from "node:http";
import { createReadStream, existsSync } from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { qrModules } from "nanoodle";
import { createDispatcher } from "./server.mjs";
import { renderCost } from "./tools.mjs";

const MAX_BODY = 32 * 1024 * 1024; // media inputs may ride inline as data: URLs

const OUT_MIME = {
  png: "image/png", jpg: "image/jpeg", gif: "image/gif", webp: "image/webp",
  mp3: "audio/mpeg", wav: "audio/wav", ogg: "audio/ogg", aac: "audio/aac", flac: "audio/flac", m4a: "audio/mp4",
  mp4: "video/mp4", webm: "video/webm", mov: "video/quicktime",
};

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

/* Brand assets, shipped with the package. Icon and OG card were themselves
 * generated by nanoodle workflows (the served `favicon` graph and og-card). */
const ASSET_DIR = fileURLToPath(new URL("../assets/", import.meta.url));
const ASSETS = {
  "/favicon.ico": "image/x-icon",
  "/favicon.png": "image/png",
  "/apple-touch-icon.png": "image/png",
  "/icon-512.png": "image/png",
  "/og.jpg": "image/jpeg",
};
const ICON_LINKS =
  `<link rel="icon" href="/favicon.ico" sizes="16x16 32x32 48x48">` +
  `<link rel="icon" type="image/png" href="/favicon.png">` +
  `<link rel="apple-touch-icon" href="/apple-touch-icon.png">`;
const OG_IMAGE_ALT = "A glowing teal bowl of noodles on a dark background, a Nano coin dropping in, " +
  "noodle strands wiring it to image, video, text, and audio nodes.";

/** QR matrix → crisp inline SVG (one path, viewBox-scaled). */
export function qrSvg(text) {
  const m = qrModules(text);
  const n = m.length;
  const margin = 3;
  let d = "";
  for (let y = 0; y < n; y++) {
    for (let x = 0; x < n; x++) if (m[y][x]) d += `M${x + margin} ${y + margin}h1v1h-1z`;
  }
  const size = n + margin * 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" shape-rendering="crispEdges">` +
    `<rect width="${size}" height="${size}" fill="#fff"/><path d="${d}" fill="#000"/></svg>`;
}

const PAGE_CSS = `
  :root{color-scheme:light dark;--fg:#1a1a1a;--bg:#fafafa;--muted:#666;--card:#fff;--edge:#e2e2e2;--ok:#0a8f4a}
  @media(prefers-color-scheme:dark){:root{--fg:#eee;--bg:#141414;--muted:#9a9a9a;--card:#1e1e1e;--edge:#333;--ok:#3ecf7a}}
  *{box-sizing:border-box}body{margin:0;font:16px/1.5 system-ui,sans-serif;color:var(--fg);background:var(--bg);
    display:flex;justify-content:center;padding:2rem 1rem}
  main{max-width:44rem;width:100%}
  .card{background:var(--card);border:1px solid var(--edge);border-radius:12px;padding:1.5rem;margin:1rem 0}
  h1{font-size:1.4rem;margin:0 0 .25rem}h2{font-size:1.05rem}
  .muted{color:var(--muted);font-size:.9rem}
  code,pre{font:.85rem/1.5 ui-monospace,monospace;background:rgba(128,128,128,.12);border-radius:6px}
  code{padding:.1rem .35rem;word-break:break-all}
  pre{padding:.75rem 1rem;overflow-x:auto}
  button{font:inherit;padding:.35rem .8rem;border-radius:8px;border:1px solid var(--edge);background:var(--card);color:var(--fg);cursor:pointer}
  .qr{width:min(280px,80vw);margin:1rem auto;display:block;border-radius:8px;overflow:hidden}
  .amount{font-size:1.6rem;font-weight:600;text-align:center}
  .ok{color:var(--ok)}
  .center{text-align:center}
  ul{padding-left:1.2rem}li{margin:.35rem 0}
`;

/*
 * The landing page commits to a dark look (the pay pages stay theme-following):
 * its job is a first impression, and the hero is one copyable command.
 */
const LANDING_CSS = `
  :root{--fg:#e6edf3;--bg:#0d1117;--muted:#8b949e;--card:#161b22;--edge:#2a313a;--accent:#2dd4bf}
  *{box-sizing:border-box}
  body{margin:0;font:16px/1.55 system-ui,sans-serif;color:var(--fg);background:var(--bg)}
  main{max-width:56rem;margin:0 auto;padding:1.25rem 1rem 3rem}
  a{color:var(--accent)}
  code{font:.85em/1.5 ui-monospace,monospace;background:rgba(139,148,158,.14);border-radius:6px;padding:.1rem .35rem;word-break:break-all}
  pre{font:.85rem/1.5 ui-monospace,monospace;background:rgba(139,148,158,.14);border-radius:6px;padding:.75rem 1rem;overflow-x:auto}
  .muted{color:var(--muted);font-size:.9rem}
  .top{display:flex;align-items:baseline;gap:.75rem;padding-bottom:2rem}
  .top .v{color:var(--muted);font-size:.85rem}
  .top nav{margin-left:auto;display:flex;gap:1rem;font-size:.9rem}
  .top nav a{color:var(--muted);text-decoration:none}
  .top nav a:hover{color:var(--fg)}
  .brand{font-weight:700;font-size:1.05rem;color:var(--fg);text-decoration:none;display:inline-flex;align-items:center;gap:.5rem}
  .brand img{width:22px;height:22px;border-radius:6px;display:block}
  .eyebrow{color:var(--accent);font:600 .78rem/1 ui-monospace,monospace;letter-spacing:.18em;text-transform:uppercase;text-align:center;margin:1.5rem 0 .6rem}
  h1{font-size:clamp(2rem,6vw,3rem);margin:0;text-align:center;letter-spacing:-.02em}
  .sub{color:var(--muted);text-align:center;margin:.75rem auto 2rem;max-width:40rem}
  .connect-wrap{display:flex;flex-direction:column;gap:.65rem}
  .tabs{display:flex;justify-content:center;gap:.35rem}
  .tabs .tab{font:inherit;font-size:.8rem;padding:.35rem .85rem;border-radius:999px;border:1px solid var(--edge);
    background:transparent;color:var(--muted);cursor:pointer}
  .tabs .tab:hover{border-color:var(--accent);color:var(--fg)}
  .tabs .tab.on{border-color:var(--accent);background:rgba(45,212,191,.12);color:var(--accent)}
  .connect{display:flex;align-items:center;gap:1rem;background:var(--card);border:1px solid var(--accent);
    border-radius:14px;box-shadow:0 0 28px rgba(45,212,191,.16);padding:1rem 1.25rem}
  .connect pre{margin:0;padding:0;background:none;flex:1;white-space:pre-wrap;overflow-wrap:anywhere;overflow-x:hidden;font-size:.95rem;color:var(--accent)}
  button{font:inherit;font-size:.85rem;padding:.4rem .9rem;border-radius:8px;border:1px solid var(--edge);
    background:var(--card);color:var(--fg);cursor:pointer;flex:none}
  button:hover{border-color:var(--accent)}
  .hint{color:var(--muted);font-size:.85rem;text-align:center;margin:.75rem 0 2.25rem}
  .steps{display:grid;grid-template-columns:repeat(auto-fit,minmax(13rem,1fr));gap:1rem;margin-bottom:2.25rem}
  .step{background:var(--card);border:1px solid var(--edge);border-radius:12px;padding:1rem 1.1rem}
  .step .n{display:inline-block;background:rgba(45,212,191,.14);color:var(--accent);border-radius:6px;
    font:600 .78rem/1 ui-monospace,monospace;padding:.3rem .45rem;margin-right:.5rem}
  .step p{margin:.6rem 0 0;color:var(--muted);font-size:.85rem}
  .flow{display:flex;flex-wrap:wrap;justify-content:center;align-items:center;gap:.6rem;background:var(--card);
    border:1px solid var(--edge);border-radius:12px;padding:.9rem 1rem;font:.85rem/1.5 ui-monospace,monospace}
  .flow .arr{color:var(--accent)}
  .tagline{text-align:center;color:var(--muted);font-size:.9rem;margin:.75rem 0 0}
  h2{font-size:1.15rem;margin:2.5rem 0 .5rem}
  .tools{display:grid;grid-template-columns:repeat(auto-fill,minmax(19rem,1fr));gap:1rem;padding:0;margin:1rem 0 0;list-style:none}
  .tool{background:var(--card);border:1px solid var(--edge);border-radius:12px;padding:1rem 1.1rem;display:flex;flex-direction:column}
  .tool p{margin:.5rem 0}
  .tool .links{font-size:.85rem;white-space:nowrap}
  .tool .thead{display:flex;align-items:baseline;justify-content:space-between;gap:.6rem}
  .tool .tname{font-weight:700;font-size:1.02rem}
  .tool .tid{font-size:.72rem;color:var(--muted)}
  .tool .intent{color:var(--muted);font-size:.88rem;margin:.45rem 0 .7rem}
  .chain{display:flex;flex-wrap:wrap;align-items:center;gap:.3rem .35rem;margin:0 0 .8rem}
  .chain .arr{color:var(--muted);font-size:.75rem}
  .chip{font:.72rem/1 ui-monospace,monospace;padding:.28rem .45rem;border-radius:7px;background:rgba(139,148,158,.14);color:#9aa4ae;white-space:nowrap}
  .chip.k-text{background:rgba(167,139,250,.14);color:#c4b5fd}
  .chip.k-llm{background:rgba(45,212,191,.13);color:#5eead4}
  .chip.k-image{background:rgba(251,191,36,.12);color:#fcd34d}
  .chip.k-video{background:rgba(251,113,133,.13);color:#fda4af}
  .chip.k-audio{background:rgba(74,222,128,.12);color:#86efac}
  .tool .tfoot{display:flex;flex-wrap:wrap;align-items:baseline;justify-content:space-between;gap:.25rem .75rem;margin-top:auto}
  .tool .cost{font:.75rem/1.4 ui-monospace,monospace;color:var(--muted);white-space:nowrap}
  .card{background:var(--card);border:1px solid var(--edge);border-radius:12px;padding:1.25rem 1.4rem;margin-top:1rem}
  .card h2{margin-top:0}
  footer{margin-top:3rem;padding-top:1.25rem;border-top:1px solid var(--edge);color:var(--muted);font-size:.85rem;text-align:center}
`;

const htmlPage = (title, body, css = PAGE_CSS, head = "") =>
  `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">` +
  `<title>${esc(title)}</title>${ICON_LINKS}${head}<style>${css}</style></head><body><main>${body}</main></body></html>`;

/** "auto-dub" → "Auto dub": the card title for humans; the exact tool id rides beside it. */
const toolTitle = (name) => {
  const s = String(name).replace(/-/g, " ");
  return s.charAt(0).toUpperCase() + s.slice(1);
};

/**
 * One-line "register this server" commands for the clients that ship an
 * `mcp add --transport http` CLI. Same endpoint, same flag shape — only the
 * binary name changes. Landing page defaults to Claude; a toggle flips to Grok.
 */
const connectCmds = (publicBase) => ({
  claude: `claude mcp add --transport http noodles ${publicBase}/mcp`,
  grok: `grok mcp add --transport http noodles ${publicBase}/mcp`,
});

function landingHtml({ name, version, listTools, publicBase, charged, toolInfo = [], costs = {} }) {
  const tools = listTools().filter((t) => t.name !== "run_noodle");
  const infoByName = new Map(toolInfo.map((t) => [t.name, t]));
  const cmds = connectCmds(publicBase);
  const cmd = cmds.claude;
  const cards = tools.map((t) => {
    const info = infoByName.get(t.name);
    const links = info ? `<span class="links"><a href="${esc(info.editorUrl)}">open in editor</a>` +
      ` · <a href="/graph/${esc(encodeURIComponent(t.name))}.json">graph JSON</a></span>` : "";
    const author = info && info.x402 && info.x402.author
      ? `<p class="muted">author payout: <code>${esc(info.x402.author)}</code></p>` : "";
    const card = info && info.card;
    // No structured pieces (a bare toolInfo entry) → the one-line description stands in.
    if (!card || !card.intent && !card.steps.length) {
      return `<li class="tool"><code>${esc(t.name)}</code><p class="muted">${esc(t.description)}</p>` +
        `${links ? `<div class="tfoot">${links}</div>` : ""}${author}</li>`;
    }
    /*
     * The card lays the description's pieces out as layers instead of one blob:
     * title → plain-words intent → tinted pipeline chips → cost + links. The
     * shared payment contract lives once above the grid, not on every card —
     * agents still get the full per-tool contract via tools/list and /llms.txt.
     */
    const chips = card.steps.map((s) =>
      `<span class="chip k-${esc(s.kind)}">${esc(s.n > 1 ? `${s.label}×${s.n}` : s.label)}</span>`
    ).join(`<span class="arr">→</span>`);
    const cost = renderCost(costs[t.name]);
    return `<li class="tool">` +
      `<div class="thead"><span class="tname">${esc(toolTitle(t.name))}</span><code class="tid">${esc(t.name)}</code></div>` +
      `<p class="intent">${esc(card.intent || t.description)}</p>` +
      (card.steps.length ? `<div class="chain">${chips}</div>` : "") +
      `<div class="tfoot"><span class="cost">${esc(cost)}</span>${links}</div>${author}</li>`;
  }).join("");
  const tagline = charged ? "AI workflows, paid in Nano over x402" : "AI media workflows over MCP";
  const desc = charged
    ? "AI workflows paid in Nano over x402 — image, video, audio, and text pipelines behind one MCP endpoint. No account, no API key."
    : "AI media workflows — image, video, audio, and text — behind one MCP endpoint. No account, no API key.";
  const ogHead =
    `<meta name="description" content="${esc(desc)}">` +
    `<meta property="og:type" content="website">` +
    `<meta property="og:site_name" content="${esc(name)}">` +
    `<meta property="og:title" content="${esc(name)} — ${esc(tagline)}">` +
    `<meta property="og:description" content="${esc(desc)}">` +
    `<meta property="og:url" content="${esc(publicBase)}/">` +
    `<meta property="og:image" content="${esc(publicBase)}/og.jpg">` +
    `<meta property="og:image:width" content="1200"><meta property="og:image:height" content="630">` +
    `<meta property="og:image:alt" content="${esc(OG_IMAGE_ALT)}">` +
    `<meta name="twitter:card" content="summary_large_image">` +
    `<meta name="twitter:title" content="${esc(name)} — ${esc(tagline)}">` +
    `<meta name="twitter:description" content="${esc(desc)}">` +
    `<meta name="twitter:image" content="${esc(publicBase)}/og.jpg">`;
  return htmlPage(name, `
    <header class="top">
      <a class="brand" href="/"><img src="/favicon.png" alt="">${esc(name)}</a><span class="v">v${esc(version)}</span>
      <nav><a href="https://nanoodle.com">editor</a><a href="https://github.com/nanoodlecom/nanoodle-mcp">github</a><a href="/llms.txt">llms.txt</a></nav>
    </header>
    <p class="eyebrow">public MCP server</p>
    <h1>${charged ? "AI workflows, paid in Nano over x402." : "AI media workflows over MCP."}</h1>
    <p class="sub">Image, video, audio, and text pipelines behind one MCP endpoint.
      ${charged ? "No account, no API key — paying is the whole handshake." : "No account, no API key."}
      Built with <a href="https://nanoodle.com">nanoodle</a>.</p>
    <div class="connect-wrap">
      <div class="tabs" role="tablist" aria-label="MCP client">
        <button type="button" class="tab on" role="tab" aria-selected="true" data-client="claude" onclick="selectClient(this)">Claude</button>
        <button type="button" class="tab" role="tab" aria-selected="false" data-client="grok" onclick="selectClient(this)">Grok</button>
      </div>
      <div class="connect"><pre id="cmd">${esc(cmd)}</pre><button type="button" onclick="copyCmd(this)">copy</button></div>
    </div>
    <p class="hint">works with Claude Code, Grok, Cursor, and any MCP client</p>
    <div class="steps">
      <div class="step"><span class="n">01</span><b>paste the command</b>
        <p>one line registers every workflow with your agent.</p></div>
      <div class="step"><span class="n">02</span><b>ask for what you want</b>
        <p>your agent picks a workflow and calls it — a poster, a soundtrack, an OG card.</p></div>
      ${charged ? `<div class="step"><span class="n">03</span><b>pay per call</b>
        <p>settled automatically in Nano. failed runs are refunded.</p></div>`
      : `<div class="step"><span class="n">03</span><b>results stream back</b>
        <p>media arrives as links, usually in seconds.</p></div>`}
    </div>
    ${charged ? `<div class="flow"><span>agent calls tool</span><span class="arr">→</span><span>402 payment quote</span>
      <span class="arr">→</span><span>wallet pays XNO · feeless · ~1s</span><span class="arr">→</span><span>result streams back</span></div>
    <p class="tagline">No tab, no tip, no signup.</p>
    <div class="card"><h2>What a call costs</h2>
      <p class="muted">When a tool needs payment, your agent shows you a link with a QR code — scan it with
      any Nano wallet and the result streams back seconds later. What you pay up front is a
      <strong>deposit</strong>: each run settles at the model's metered cost + 20%, and the difference is
      returned to your wallet on-chain. The 20% is the <strong>workflow author's cut</strong>, not a platform fee.</p>
    </div>` : ""}
    <h2>Workflows (${tools.length})</h2>
    <p class="muted">Every workflow is a plain <code>noodle-graph.json</code> — open it in the
      <a href="https://nanoodle.com">nanoodle editor</a> to see exactly how it works, remix it, or run it
      on your own key.${charged ? " Costs shown are the last observed run — each call is a small deposit that settles at the model's actual cost + 20%, change returned." : ""}</p>
    <ul class="tools">${cards}</ul>
    <div class="card"><h2>Private by design</h2>
      <p class="muted">Every line here is checkable in the source — nothing to take on faith.</p>
      <ul>
        <li>No accounts, no API keys, no sign-ins${charged ? " — paying is the only thing that authorizes a call" : ""}.</li>
        <li>Your prompts and inputs are never written to disk or logs.</li>
        <li>Input media rides in memory only — it is never stored.</li>
        <li>Generated media auto-deletes after 24 hours, served at unguessable URLs until then.</li>
        <li>Results are held in memory for delivery, not stored.</li>
        <li>No analytics, no trackers, no IP logs — the server keeps no request logs.</li>
        ${charged ? `<li>The only thing written down is a payments ledger: money events that mirror what is already public on the Nano ledger — no run telemetry, no error text.</li>` : ""}
      </ul>
      <p class="muted">One caveat, stated plainly: generation runs on <a href="https://nano-gpt.com">NanoGPT</a>'s API,
        so your prompt content in flight is governed by <a href="https://nano-gpt.com/privacy">their privacy policy</a>.</p>
      <p class="muted"><a href="https://github.com/nanoodlecom/nanoodle-mcp">Verify every line in the source →</a></p>
    </div>
    ${charged ? `<div class="card"><h2>Workflow authors earn the 20%</h2>
      <p class="muted">A graph that declares a Nano address (<code>"x402": {"author": "nano_…"}</code> in its
      JSON) receives the full 20% markup of every paid run, paid out on-chain automatically. The public
      library behind this server is <a href="https://github.com/nanoodlecom/awesome-noodles">awesome-noodles</a> —
      add your workflow there with your address to get listed and earn on every run.</p>
    </div>` : ""}
    <div class="card"><h2>Open source — host your own</h2>
      <p class="muted">This whole stack is MIT-licensed: the
      <a href="https://github.com/nanoodlecom/nanoodle-mcp">server</a>, the
      <a href="https://github.com/nanoodlecom/nanoodle">editor</a>, and every workflow above
      (grab any graph JSON). One command turns your own folder of graphs into a server exactly like this one:</p>
      <pre>npx nanoodle-mcp --graphs ./noodles --serve 8402</pre>
      <p class="muted">Add <code>--charge-usd 0.05 --public-url https://your-host</code> and a Nano wallet to
      charge per call — see the <a href="https://github.com/nanoodlecom/nanoodle-mcp#serve-mode--host-your-noodles-as-a-service---serve">README</a>.</p>
    </div>
    <footer>agents: this page as plain text at <a href="/llms.txt">/llms.txt</a></footer>
    <script>
      const CMDS = ${JSON.stringify(cmds)};
      function selectClient(btn){
        const id = btn.getAttribute("data-client");
        if (!CMDS[id]) return;
        document.getElementById("cmd").textContent = CMDS[id];
        document.querySelectorAll(".tabs .tab").forEach((b) => {
          const on = b === btn;
          b.classList.toggle("on", on);
          b.setAttribute("aria-selected", on ? "true" : "false");
        });
      }
      function copyCmd(b){
        navigator.clipboard.writeText(document.getElementById("cmd").textContent).then(() => {
          b.textContent = "copied";
          setTimeout(() => { b.textContent = "copy"; }, 1200);
        });
      }
    </script>
  `, LANDING_CSS, ogHead);
}

/** The landing page's story as plain text — the version an agent should read. */
function llmsTxt({ name, version, listTools, publicBase, charged, toolInfo = [] }) {
  const tools = listTools().filter((t) => t.name !== "run_noodle");
  const infoByName = new Map(toolInfo.map((t) => [t.name, t]));
  const lines = [
    `# ${name} v${version}`,
    ``,
    charged
      ? `Public MCP server: AI workflows (image, video, audio, text) paid per call in Nano over x402 — built with nanoodle (https://nanoodle.com).`
      : `Public MCP server: AI media workflows (image, video, audio, text) built with nanoodle (https://nanoodle.com).`,
    ``,
    `endpoint: ${publicBase}/mcp (MCP streamable HTTP — POST JSON-RPC, SSE progress on tools/call)`,
    `connect (Claude): claude mcp add --transport http noodles ${publicBase}/mcp`,
    `connect (Grok):   grok mcp add --transport http noodles ${publicBase}/mcp`,
    ``,
  ];
  if (charged) {
    lines.push(
      `## Payment (x402, Nano/XNO)`,
      ``,
      `- No accounts, no API keys. Each tools/call answers with a payment quote: an exact XNO amount, a nano: URI, and a payUrl (${publicBase}/pay/<id>). Show the user ONLY the payUrl.`,
      `- Send exactly the quoted amount (the amount identifies the payment), then IMMEDIATELY call again with the returned _payment_id — right after showing the link, do not wait for the user to say "go". On a streaming transport (Accept: text/event-stream) that call blocks (held open with heartbeats) until the payment lands, then runs. Paying is the consent; the result object carries "blocking":true and a "next" imperative saying exactly this. That call is how you watch for the payment.`,
      `- Agent-only (never show the user): to watch a payment settle yourself, subscribe to the SSE stream ${publicBase}/x402/watch/<id> (one status event per state change) or poll ${publicBase}/x402/status/<id>?wait=1.`,
      `- The quote is a deposit: the run settles at metered model cost + 20%, and the difference returns to the payer on-chain. Failed runs are refunded automatically.`,
      `- The 20% is the workflow author's cut, not a platform fee.`,
      ``,
    );
  }
  lines.push(`## Tools`, ``);
  for (const t of tools) {
    lines.push(`- ${t.name}: ${t.description}`);
    if (infoByName.has(t.name)) lines.push(`  graph: ${publicBase}/graph/${encodeURIComponent(t.name)}.json`);
  }
  lines.push(
    ``,
    `## Privacy`,
    ``,
    `Relay this to anyone deciding whether to pay — every line is verifiable in the MIT-licensed source.`,
    `- No accounts, no API keys, no sign-ins${charged ? " — paying is the only thing that authorizes a call" : ""}.`,
    `- Prompts and inputs are never written to disk or logs.`,
  );
  if (charged) lines.push(`- The server keeps only a short hash binding a payment to its call, never the arguments themselves.`);
  lines.push(
    `- Input media is held in memory only, never stored.`,
    `- Generated media auto-deletes after 24h (the --out-ttl default in serve mode), served at unguessable URLs until then.`,
    `- Results are held in memory for delivery, not stored.`,
    `- No analytics, trackers, IP logs, or access logs — the server keeps no request logs.`,
  );
  if (charged) lines.push(`- The only log is a payments ledger (usage.jsonl): money-lifecycle events that mirror the public Nano ledger — no run telemetry, no error text.`);
  lines.push(
    `- Caveat: generation runs on NanoGPT's API (https://nano-gpt.com), so prompt content in flight is governed by their privacy policy (https://nano-gpt.com/privacy).`,
    ``,
    `## Source`,
    ``,
    `MIT-licensed end to end: server https://github.com/nanoodlecom/nanoodle-mcp, editor https://github.com/nanoodlecom/nanoodle, workflow library https://github.com/nanoodlecom/awesome-noodles.`,
    `Self-host: npx nanoodle-mcp --graphs ./noodles --serve 8402`,
    ``,
  );
  return lines.join("\n");
}

function payPageHtml(q) {
  const statusUrl = `/x402/status/${encodeURIComponent(q.id)}?wait=1`;
  const watchUrl = `/x402/watch/${encodeURIComponent(q.id)}`;
  return htmlPage(`Pay ${q.amountXno} XNO`, `
    <div class="card center" id="paybox">
      <h1>Pay ${esc(q.amountXno)} XNO <span class="muted">(≈$${esc(q.usd.toFixed(q.usd < 0.01 ? 4 : 2))})</span></h1>
      <p class="muted">for one run of <code>${esc(q.tool)}</code> — scan with any Nano wallet</p>
      <a class="qr" href="${esc(q.uri)}">${qrSvg(q.uri)}</a>
      <p><button onclick="navigator.clipboard.writeText('${esc(q.address)}')">copy address</button>
         <button onclick="navigator.clipboard.writeText('${esc(q.amountXno)}')">copy amount</button></p>
      <p class="muted">Send <strong>exactly ${esc(q.amountXno)} XNO</strong> — the exact amount identifies your payment.<br>
         Address: <code>${esc(q.address)}</code><br>Amount: <code>${esc(q.amountXno)}</code> XNO (<code>${esc(q.amountRaw)}</code> raw)</p>
      <p class="muted" id="status">waiting for payment… settles in about a second</p>
      <p class="muted" id="expiry"></p>
    </div>
    <script>
      const EXP = Date.parse(${JSON.stringify(q.expiresAt)});
      function tickExpiry(){
        const el = document.getElementById("expiry");
        if(!el) return; // paybox was replaced by the paid check
        const s = Math.max(0, Math.floor((EXP - Date.now())/1000));
        el.textContent = s > 0
          ? "quote expires in " + Math.floor(s/60) + ":" + String(s%60).padStart(2,"0")
          : "quote expired — ask your agent for a fresh one";
        if(s > 0) setTimeout(tickExpiry, 1000);
      }
      tickExpiry();
    </script>
    <script>
      var done = false;
      function apply(status){
        if(done) return false;
        if(status === "paid" || status === "consumed"){
          done = true;
          document.getElementById("paybox").innerHTML =
            '<h1 class="ok">✓ Paid</h1><p>All set — go back to your terminal, the result is on its way.</p>';
          return true;
        }
        if(status === "expired" || status === "unknown"){
          done = true;
          document.getElementById("status").textContent = "this quote expired — ask your agent for a fresh one";
          return true;
        }
        return false;
      }
      // Prefer the server-push watch stream; fall back to polling if EventSource
      // is unavailable or the stream errors (proxy, old browser, at capacity).
      async function poll(){
        while(!done){
          try{
            const r = await fetch(${JSON.stringify(statusUrl)});
            if(apply((await r.json()).status)) return;
          }catch{ await new Promise(function(r){ setTimeout(r, 1000); }); }
        }
      }
      function watch(){
        if(typeof EventSource === "undefined") return poll();
        var es;
        try{ es = new EventSource(${JSON.stringify(watchUrl)}); }catch(e){ return poll(); }
        es.addEventListener("status", function(ev){
          try{ if(apply(JSON.parse(ev.data).status)){ es.close(); } }catch{}
        });
        es.onerror = function(){ es.close(); if(!done) poll(); }; // stream dropped → poll
      }
      watch();
    </script>
  `);
}

/**
 * @param {object} opts
 * @param {string} opts.host  bind address (default 127.0.0.1 — use 0.0.0.0 behind a reverse proxy)
 * @param {number} opts.port
 * @param {object|null} [opts.gate]  charge gate (createChargeGate) — null serves free
 * @param {Array} [opts.toolInfo]  registry.tools — per-tool editorUrl/rawText/x402/card for the landing page and /graph/:name.json
 * @param {object} [opts.costs]  registry.costs — live last-observed-cost records, shown on the landing cards
 * @param {string|null} [opts.outDir]  when set, /out/<file> serves generated media from it
 * @param {number} [opts.progressMs]  heartbeat interval on streamed tools/call responses
 * @param {number} [opts.maxStreams]  cap on concurrently-held event streams (tools/call holds +
 *                                    /x402/watch subscribers). At the cap, new tools/call requests
 *                                    are answered as plain JSON (the pre-hold-open behaviour) and
 *                                    new watch subscriptions get a 503 so the pay page falls back to
 *                                    polling — a held-connection backstop, far above real concurrency.
 * @returns {Promise<http.Server>}
 */
export async function serveHttp({
  host = "127.0.0.1",
  port,
  name,
  version,
  listTools,
  callTool,
  instructions,
  gate = null,
  toolInfo = [],
  costs = {},
  outDir = null,
  publicBase,
  progressMs = 10_000,
  maxStreams = 4096,
  log = (...a) => console.error(...a),
}) {
  const dispatch = createDispatcher({ name, version, listTools, callTool, instructions, log });
  const graphByName = new Map(toolInfo.filter((t) => t.rawText).map((t) => [t.name, t.rawText]));

  // Every held event stream (a streaming tools/call, a /x402/watch subscriber)
  // rides the gate's ONE shared payment watcher — no per-connection polling — so
  // a parked connection costs a socket, a heartbeat timer, and a waiter slot,
  // nothing that scales with the chain. This counter is only a socket backstop.
  let activeStreams = 0;

  const server = http.createServer(async (req, res) => {
    const url = new URL(req.url, `http://${req.headers.host || "localhost"}`);
    const send = (code, body, type = "application/json") => {
      res.writeHead(code, { "Content-Type": type, "Access-Control-Allow-Origin": "*" });
      res.end(body);
    };

    try {
      if (req.method === "OPTIONS") {
        res.writeHead(204, {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
          "Access-Control-Allow-Headers": "Content-Type, Mcp-Session-Id, Mcp-Protocol-Version",
        });
        return res.end();
      }

      if (url.pathname === "/mcp") {
        if (req.method === "GET") return send(405, JSON.stringify({ error: "no server-initiated stream — POST JSON-RPC messages here" }));
        if (req.method !== "POST") return send(405, JSON.stringify({ error: "POST only" }));
        if (!/^application\/json\b/.test(req.headers["content-type"] || "")) {
          return send(415, JSON.stringify({ error: "Content-Type must be application/json" }));
        }
        const chunks = [];
        let len = 0;
        for await (const c of req) {
          len += c.length;
          if (len > MAX_BODY) return send(413, JSON.stringify({ error: "body too large" }));
          chunks.push(c);
        }
        let msg;
        try { msg = JSON.parse(Buffer.concat(chunks).toString("utf8")); }
        catch { return send(400, JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "parse error" } })); }

        /*
         * tools/call from an SSE-capable client streams: heartbeats every
         * progressMs — MCP progress notifications when the client sent a
         * progressToken (clients reset their tool timeout on these), plain SSE
         * comments otherwise (keeps proxies from idling the socket) — then the
         * final response. A generation or payment wait can take minutes; a
         * silent held-open POST is exactly what client timeouts kill.
         */
        const isCall = msg && typeof msg === "object" && msg.method === "tools/call" && msg.id !== null && msg.id !== undefined;
        // At the held-connection cap we don't refuse the call — we drop to the
        // plain-JSON path below, which still answers correctly (a paid call just
        // returns its quote to relay instead of holding open). Graceful, not a 503.
        if (isCall && activeStreams < maxStreams && /\btext\/event-stream\b/i.test(req.headers.accept || "")) {
          const progressToken = msg.params && msg.params._meta ? msg.params._meta.progressToken : undefined;
          res.writeHead(200, {
            "Content-Type": "text/event-stream",
            "Cache-Control": "no-cache",
            "Access-Control-Allow-Origin": "*",
          });
          activeStreams++;
          const event = (obj) => { if (!res.writableEnded && !res.destroyed) res.write(`event: message\ndata: ${JSON.stringify(obj)}\n\n`); };
          const t0 = Date.now();
          let ticks = 0;
          const emitProgress = (message) => {
            if (progressToken === undefined) return false; // no progress channel on this call
            event({ jsonrpc: "2.0", method: "notifications/progress", params: { progressToken, progress: ++ticks, message } });
            return true;
          };
          /*
           * ctx rides through the dispatcher to the (gated) tool:
           *   report(s)   — set the status the next heartbeat repeats
           *   announce(s) — also push that line as a progress update immediately,
           *                 not just at the next heartbeat (no-op returning false
           *                 when the call carries no progressToken). Used for
           *                 mid-run status the caller should see without waiting.
           */
          const ctx = {
            streaming: true,
            status: "working",
            report(s) { this.status = s; },
            announce(s) { this.status = s; return emitProgress(s); },
          };
          const beat = setInterval(() => {
            const line = `${ctx.status} (${Math.round((Date.now() - t0) / 1000)}s elapsed)`;
            if (!emitProgress(line) && !res.writableEnded && !res.destroyed) {
              res.write(`: ${line}\n\n`); // SSE comment — connection warmth without protocol noise
            }
          }, progressMs);
          if (beat.unref) beat.unref();
          try {
            const response = await dispatch(msg, ctx);
            if (response) event(response);
          } finally {
            clearInterval(beat);
            activeStreams--;
            if (!res.writableEnded && !res.destroyed) res.end();
          }
          return;
        }

        const response = await dispatch(msg);
        if (!response) { res.writeHead(202, { "Access-Control-Allow-Origin": "*" }); return res.end(); }
        return send(200, JSON.stringify(response));
      }

      if (req.method !== "GET" && req.method !== "HEAD") return send(405, JSON.stringify({ error: "method not allowed" }));

      if (url.pathname === "/") {
        return send(200, landingHtml({ name, version, listTools, publicBase, charged: !!gate, toolInfo, costs }), "text/html; charset=utf-8");
      }

      if (url.pathname === "/llms.txt") {
        return send(200, llmsTxt({ name, version, listTools, publicBase, charged: !!gate, toolInfo }), "text/plain; charset=utf-8");
      }

      if (ASSETS[url.pathname]) {
        const path = join(ASSET_DIR, basename(url.pathname));
        if (!existsSync(path)) return send(404, JSON.stringify({ error: "not found" }));
        res.writeHead(200, {
          "Content-Type": ASSETS[url.pathname],
          "Access-Control-Allow-Origin": "*",
          "Cache-Control": "public, max-age=86400",
        });
        if (req.method === "HEAD") return res.end();
        return createReadStream(path).on("error", () => res.destroy()).pipe(res);
      }

      const graphMatch = url.pathname.match(/^\/graph\/([^/]+)\.json$/);
      if (graphMatch) {
        const raw = graphByName.get(decodeURIComponent(graphMatch[1]));
        if (!raw) return send(404, JSON.stringify({ error: "not found" }));
        return send(200, raw, "application/json; charset=utf-8");
      }

      const payMatch = url.pathname.match(/^\/pay\/([^/]+)$/);
      if (payMatch && gate) {
        const q = gate.quote(decodeURIComponent(payMatch[1]));
        if (!q) return send(404, htmlPage("Not found", "<h1>Unknown or expired payment</h1><p class=\"muted\">Ask your agent for a fresh quote.</p>"), "text/html; charset=utf-8");
        return send(200, payPageHtml(q), "text/html; charset=utf-8");
      }

      const statusMatch = url.pathname.match(/^\/x402\/status\/([^/]+)$/);
      if (statusMatch && gate) {
        const id = decodeURIComponent(statusMatch[1]);
        if (url.searchParams.get("wait")) await gate.waitForPayment(id, 25_000);
        const q = gate.quote(id);
        return send(200, JSON.stringify(q ? { status: q.status, amountRaw: q.amountRaw, expiresAt: q.expiresAt } : { status: "unknown" }));
      }

      /*
       * SSE payment watch: one `status` event per state change, closing the
       * instant the payment lands (or the quote dies). It's push, not polling —
       * the pay page subscribes to it (falling back to /x402/status polling if the
       * browser can't), and any HTTP client can too. It rides the gate's shared
       * waiter list, so a thousand subscribers still cost one chain poll. At the
       * held-connection cap it 503s and the caller falls back to polling.
       */
      const watchMatch = url.pathname.match(/^\/x402\/watch\/([^/]+)$/);
      if (watchMatch && gate) {
        const id = decodeURIComponent(watchMatch[1]);
        if (activeStreams >= maxStreams) return send(503, JSON.stringify({ error: "too many open streams — poll /x402/status instead" }));
        res.writeHead(200, {
          "Content-Type": "text/event-stream",
          "Cache-Control": "no-cache",
          "Access-Control-Allow-Origin": "*",
        });
        activeStreams++;
        let alive = true;
        req.on("close", () => { alive = false; });
        const sse = (ev, obj) => { if (alive && !res.writableEnded && !res.destroyed) res.write(`event: ${ev}\ndata: ${JSON.stringify(obj)}\n\n`); };
        const ping = setInterval(() => { if (alive && !res.writableEnded && !res.destroyed) res.write(`: ping\n\n`); }, progressMs);
        if (ping.unref) ping.unref();
        try {
          let q = gate.quote(id);
          sse("status", q ? { status: q.status, amountRaw: q.amountRaw, expiresAt: q.expiresAt } : { status: "unknown" });
          // Hold the stream open across state changes until the quote settles or
          // the client leaves. Each wait resolves on the shared watcher firing
          // (paid/expired) or its own 25s ceiling — a re-poll that also lets a
          // dropped connection be noticed and cleaned up.
          const deadline = Date.now() + 20 * 60 * 1000; // never outlive a quote (15m TTL + slack)
          while (alive && q && q.status === "pending" && Date.now() < deadline) {
            await gate.waitForPayment(id, 25_000);
            q = gate.quote(id);
            if (q) sse("status", { status: q.status, amountRaw: q.amountRaw, expiresAt: q.expiresAt });
          }
        } finally {
          clearInterval(ping);
          activeStreams--;
          if (!res.writableEnded && !res.destroyed) res.end();
        }
        return;
      }

      const outMatch = url.pathname.match(/^\/out\/([^/]+)$/);
      if (outMatch && outDir) {
        const file = basename(decodeURIComponent(outMatch[1])); // basename() forbids traversal
        const path = join(outDir, file);
        if (!existsSync(path)) return send(404, JSON.stringify({ error: "not found" }));
        const ext = file.split(".").pop().toLowerCase();
        res.writeHead(200, {
          "Content-Type": OUT_MIME[ext] || "application/octet-stream",
          "Access-Control-Allow-Origin": "*",
          "Cache-Control": "private, max-age=86400",
        });
        if (req.method === "HEAD") return res.end();
        return createReadStream(path).on("error", () => res.destroy()).pipe(res);
      }

      return send(404, JSON.stringify({ error: "not found" }));
    } catch (e) {
      log(`nanoodle-mcp: http error on ${req.method} ${req.url}: ${(e && e.stack) || e}`);
      if (!res.headersSent) send(500, JSON.stringify({ error: "internal error" }));
      else res.destroy();
    }
  });

  await new Promise((resolve, reject) => {
    server.once("error", reject);
    server.listen(port, host, resolve);
  });
  return server;
}
